### ISSUE TITLE
Documentation: determining whether something is a high risk accessibility concern

### ISSUE THREAD

**Issue by dav-idc** [alphagov/design-system-team-docs#35]
## What
Add a flowchart-type set of documentation on the process of determining a 
## Why
- helps expand on the prioritisation info on the accessibility strategy
- allows more team members beyond the accessibility specialist to carry out an assessment of accessibility risk
- standardises our format for recording accessibility risk in GitHub issues

This is related to a broader epic about adding accessibility documentation to our playbook:
- https://github.com/alphagov/govuk-design-system/issues/3077

## Who's doing work on this
Accessibility specialist

## Who should review
Developers, other team members

```[tasklist]
### Tasks
- [ ] Gather examples of existing assessments
- [ ] Create a template for assessments
- [ ] Write instruction steps for making the assessment
- [ ] Create a flowchart for when to do this risk assessment and when it's not so necessary
- [ ] Write intro and background info, linking to accessibility strategy
- [ ] Send for review by the team
```

**Comment by dav-idc** [comment]
This will not be completed by me before I leave GDS 😢 

I recommend handing this to the next accessibility specialist.

FYI @kellylee-gds @stevenjmesser
